chat_app/config/routes.rb
FayeTutorial::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root :to => "home#index"

  match '/register',    to: 'users#new'
  match '/logout', to: 'sessions#destroy', via: :delete

  get  '/contact' => 'home#contact.html.erb'

  get "chats/room"

  get "sessions/new"

  get "sessions/create"

  get  '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create', :as => :login  
  get  '/chatroom' => 'chats#room', :as => :chat  

end

chat_app/app/models/session.rb
class Session < ActiveRecord::Base
  # attr_accessible :title, :body
end

chat_app/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

chat_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    logout
    super
  end
end

chat_app/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def room
    redirect_to login_path unless session[:username]
  end
end

chat_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def contact
  end
end

chat_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session[:username] = params[:username]
    render :text => "Welcome #{session[:username]}!"
  end
end

chat_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :logged_in_user,  only: [:index, :show, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def new
	@user = User.new
  end
  def show
	@user = User.find(params[:id])
  end
  def create
    @user = User.new(params[:user])
    if @user.save
	  login @user
	  flash[:success] = "Welcome! You are registered."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      login @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  private

    def logged_in_user
      unless logged_in?
        store_location
        redirect_to login_url, notice: "Please sign in."
      end
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

	def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

chat_app/app/helpers/application_helper.rb
module ApplicationHelper
end

chat_app/app/helpers/chats_helper.rb
module ChatsHelper
end

chat_app/app/helpers/home_helper.rb
module HomeHelper
end

chat_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

chat_app/app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

chat_app/app/views/chats/room.html.erb
<% provide(:title, 'Chat room') %>
<script>
  $(function() {
    // Create a new client to connect to Faye
	<% if Rails.env.production? %>
	var client = new Faye.Client("http://88.198.9.226:4021/faye");
	<% else %>
    var client = new Faye.Client("http://localhost:9292/faye");
	<% end %>

    // Subscribe to the public channel
    var public_subscription = client.subscribe('/messages/public', function(data) {
      $('<p></p>').html(data.username + ": " + data.msg).appendTo('#chat_room');
    });
 
    // Handle form submissions and post messages to faye
    $('#new_message_form').submit(function(){
      // Publish the message to the public channel
      client.publish('/messages/public', {
        username: '<%= current_user.name %>',
        msg: $('#message').val()
      });
 
      // Clear the message box
      $('#message').val('');
 
      // Don't actually submit the form, otherwise the page will refresh.
      return false;
    });
  });
</script>
<h1>Chat room</h1>
<div class="chat_container">
  <div id="chat_room">
    <p class="alert"> Welcome to the chat room <%= current_user.name %>! </p>
  </div>
 
  <form id="new_message_form">
    <input type="text" id="message" name="message">
    <input type="submit" value="Send">
  </form>
</div>

chat_app/app/views/home/contact.html.erb
<% provide(:title, 'Contact') %>
<h1> Contact </h1>
<h2>
	If you have any questions: georgi.olentsenko@gmail.com      
</h2>

chat_app/app/views/home/index.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Welcome to the Chat</h1>


<% if logged_in? %>
<p><%= link_to "Go to chat room", chat_path %></p>
<p><%= link_to "Show users", users_path %></p>    
<% else %>
<h1><%= link_to "Login", login_path, class: "btn btn-large btn-primary" %></h1>
<p>New user? <%= link_to "Register now!", register_path %></p>
<% end %>
  
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

chat_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "CHAT", root_path, id: "logo" %>
	  <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
		  <li><%= link_to "Chat room", chat_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 <%= current_user.name %>'s Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Change information", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Logout", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

chat_app/app/views/layouts/application.html.erb
<!DOCTYPE html>

<% if Rails.env.production? %>
<%= javascript_include_tag "http://88.198.9.226:4021/faye.js" %>
<% else %>
<%= javascript_include_tag "http://localhost:9292/faye.js" %>
<% end %>

<html>
	<head>
	   	<title> Chat | <%= yield(:title) %></title>
	  	<%= stylesheet_link_tag    "application", :media => "all" %>
	  	<%= javascript_include_tag "application" %>
	  	<%= csrf_meta_tags %>
	  	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<%= render 'layouts/header' %>

		<div class="container">
		  <% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
		  <% end %>
		  <%= yield %>
		</div>

	<%= debug(params) if Rails.env.development? %>

	</body>
</html>

chat_app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

chat_app/app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

chat_app/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

chat_app/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
	<%= render user %>
  <% end %>
</ul>

<%= will_paginate %>

chat_app/app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<h1>Registering new user</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
	  <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

chat_app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
<%= @user.email %>